# Generated by Django 5.2.3 on 2025-06-28 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='mood',
            field=models.CharField(choices=[('happy', '😊 Happy'), ('sad', '😢 Sad'), ('anxious', '😰 Anxious'), ('angry', '😡 Angry')], default='happy', max_length=20),
        ),
    ]
