# Generated by Django 5.2.3 on 2025-06-28 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_entry_mood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='mood',
            field=models.CharField(choices=[('happy', '😊 Happy & Joyful'), ('sad', '😢 Sad & Melancholy'), ('excited', '🎉 Excited & Energetic'), ('calm', '😌 Calm & Peaceful'), ('anxious', '😰 Anxious & Worried'), ('grateful', '🙏 Grateful & Thankful'), ('reflective', '🤔 Reflective & Thoughtful'), ('creative', '🎨 Creative & Inspired'), ('nostalgic', '💭 Nostalgic & Reminiscent')], default='happy', max_length=20),
        ),
    ]
