# Generated by Django 5.2.3 on 2025-06-28 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_entry_mood'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='is_dead',
        ),
        migrations.AddField(
            model_name='entry',
            name='renewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
