# Generated by Django 5.2.3 on 2025-06-28 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_entry_is_dead_entry_renewed_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='renewed_at',
        ),
        migrations.AddField(
            model_name='entry',
            name='is_dead',
            field=models.BooleanField(default=False),
        ),
    ]
